import 'package:box_canvas/box_canvas.dart';

/// Given an [entityPosition] and [response] return an id
///
/// the [proposedId] is the id that was generated by the canvas
/// as some callbacks may want to use that id
typedef CustomEntityIdCallback<T> = String Function(
    {required String proposedId,
    required EntityPosition position,
    required AddEntityResponse<T> info});
